### ISSUE TITLE
Отчёт по файлам, которые не принадлежат владельцу каталога

### ISSUE THREAD

**Issue by otsheln1k** [moevm/nosql2h21-google-drive#9]
В том числе:

- фрагмент на панельки с запросами (с передачей параметров в http query, в том числе параметра "без подкаталогов")
- обработчик http-пути
- шаблон для отображения результата (с панелькой управления как слева в макетах)
- собственно, запрос к БД

**Comment by Eldar1999** [comment]
Done!
